# Generated by Django 3.2 on 2021-04-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='htmlfields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('desc1', models.TextField()),
                ('img1', models.ImageField(upload_to='imgs')),
                ('desc2', models.TextField()),
                ('img2', models.ImageField(upload_to='imgs')),
                ('desc3', models.TextField()),
            ],
        ),
    ]
